name: Fly Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip d') }}
        uses: actions/checkout@v3
      - if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip d') }}
        uses: superfly/flyctl-actions/setup-flyctl@master
      - if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip d') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
