name: Periodic Health Check

on:
  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3.1
        with:
          url: https://asvnpokedex.fly.dev/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
