name: Hello World!

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
      - name: Date
        run: |
          echo "Current date: $(date)"
      - name: Directory content
        run: |
          echo "Current directory: ls $(pwd)"
