name: Hello World!

on:
  push:
    branches:
      - master
  pull_request: // highlight-line
    branches: [master] // highlight-line
    types: [opened, synchronize] // highlight-line

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World"
      - name: Date
        run: |
          echo "Current date: $(date)"
      - name: Directory content
        run: |
          echo "Current directory: ls $(pwd)"
